apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.30
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        env:
        - name: HOST_PROC
          value: /host/proc
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  labels:
    app: telegraf
data:
  telegraf.conf: |
    # Hier Telegraf-Konfiguration einfügen
    # Beispiel: [[outputs.influxdb_v2]] ...
